-- MSSQL: CREATE DATABASE fbDB;
CREATE DATABASE fbDB;
GO
USE fbDB;
GO

CREATE TABLE Teams
(
    TeamId INT IDENTITY PRIMARY KEY,
    [Name] VARCHAR(30),
    DateFound DATE,
    Earnings DECIMAL(15, 2)
)

CREATE TABLE Athletes
(
    AthleteId INT IDENTITY PRIMARY KEY,
    FirstName VARCHAR(30),
    LastName VARCHAR(30),
    Nationality VARCHAR(50),
    Position VARCHAR(15),
    Price DECIMAL (15, 2),
    DateBorn DATE,
    TeamId INT FOREIGN KEY REFERENCES Teams(TeamId) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Matches
(
    MatchId INT IDENTITY PRIMARY KEY,
    HomeTeamId INT FOREIGN KEY REFERENCES Teams(TeamId) ON DELETE NO ACTION ON UPDATE NO ACTION,
    AwayTeamId INT FOREIGN KEY REFERENCES Teams(TeamId) ON DELETE NO ACTION ON UPDATE NO ACTION,
    HomeTeamGoals INT,
    AwayTeamGoals INT,
)